replicaCount: 3

image:
  repository: powerninjas/rancher-demo
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: rancher-demo.local
      paths:
        - path: /

